### ISSUE TITLE
Jetson TX2 onboard camera

### ISSUE THREAD

**Issue by AlexanderRobles21** [GustavZ/realtime_object_detection#1]
Hi GustavZ!

How did you configure config.yml file to open onboard camera on Jetson TX2? 

Thanks!

**Comment by Kowasaki** [comment]
Hey @AlexanderRobles21, 

I'm assuming you mean the camera from the Development Kit, but here is a step by step of how to use that camera in opencv:  http://www.jetsonhacks.com/2017/09/08/opencv-python-onboard-camera-nvidia-jetson-tx2/

**Comment by GustavZ** [comment]
closing
