### ISSUE TITLE
Optimize for inference

### ISSUE THREAD

**Issue by YaroslavSchubert** [GustavZ/realtime_object_detection#15]
Hi @GustavZ, thanks for the great work!

I saw the section about optimize for inference in you howto_wiki.
I wonder if you tried to use tensorflow.python.tools.optimize_for_inference for the current SSD-Mobilenet model and if so what are the results?

Did you also try quantization and graph transform tools?

Thank you.

**Comment by GustavZ** [comment]
Hey @YaroslavSchubert thank you!

No I did not experiment with those yet, as I am currently focusing on another project. But if you give it a try and report how the results are it would be very useful and interesting!

Cheers
Gustav

**Comment by YaroslavSchubert** [comment]
Great, will share results once done!

**Comment by GustavZ** [comment]
Yeah keep me up to date!
