### ISSUE TITLE
How to achieve 8|10 FPS on TX2

### ISSUE THREAD

**Issue by Kowasaki** [GustavZ/realtime_object_detection#2]
Hey @GustavZ ,

I have basically the exact same setup as you on the TX2 but my FPS is only half of what you have achieved. I was wondering how you were able to do so? Was the improvement mostly from adjusting the batch_non_max_suppression.score_threshold during export?

**Comment by GustavZ** [comment]
Hi @Kowasaki,
yes for the jetson that's the adjustment that brought the most performance increase.
There is a very recent issue that could be interesting for you:
https://github.com/tensorflow/models/issues/3270

**Comment by Kowasaki** [comment]
Thanks! I tried it and the frame rate did improve! I'm going to try the graph-splitting hack you linked as well and see how it goes.

**Comment by GustavZ** [comment]
Hey Kowasaki, I implemented the graph splitting.
if you pull the latest version it is included. (check for split_graph = True in the config)
I recieved nearly 15 fps without visualization on the jetson!

**Comment by Kowasaki** [comment]
Hi @GustavZ , I tried your graph splitting implementation and I was able to get 16~18FPS without using additional resources! Thanks so much for the help!

**Comment by GustavZ** [comment]
@Kowasaki now you should be able to achieve up to 30 fps ;)

**Comment by Kowasaki** [comment]
I like the thread implementation! I have a couple related questions which I posted on #4 and I would be interested in figuring out the mask situation.

**Comment by GustavZ** [comment]
closing
