### ISSUE TITLE
How can I fix it?

### ISSUE THREAD

**Issue by ViousGod** [gustavz/realtime_object_detection#37]
When I run "objectdetection_video.py", it shows "No module named 'tf_utils'".

**Comment by baicaigithub** [comment]
I don't know python really well, this fix works on me. I'm running on windows.
`import rod.tf_utils as tf_utils`

**Comment by ViousGod** [comment]
Thank you guys, I'll try it!

**Comment by echo1consulting** [comment]
@ViousGod , @baicaigithub's solution worked for me. I forked a copy and made a modification [here](https://github.com/echo1consulting/realtime_object_detection).

**Comment by echo1consulting** [comment]
I submit a PR https://github.com/GustavZ/realtime_object_detection/pull/40
