### ISSUE TITLE
Query on Performance of r1.0 version of the code

### ISSUE THREAD

**Issue by Niran89** [gustavz/realtime_object_detection#38]
Hi,
I ported the r1.0 version of the code in Jetson Tx2. I got 30 fps for a resolution of 320x240. But I observe that the frame rate is based on the number of objects in the scene. Say, for one object in the scene,  it says 30 fps whereas, for 5 to 6 objects the frame rate drops down to 20 to 25 fps. Sometime even 15fps. Is my observation correct ? Or is the code's performance depends on the number of objects too ? Also, the test images in the folder has one objects in all the images. Can you share the performance for multiple objects too. 

Thanks in advance. 
Niran

**Comment by gustavz** [comment]
The 1.0 version uses PIL (like the tensorflow object detetcion api) for image drawing.
The newer versions use openCV which is much faster and does not depend on number of detected objects.

But for both cases this is just a rendering problem, the actual detection is the same / same speed for any number of detections.
