### ISSUE TITLE
How to convert the Mask RCNN model to tflite model

### ISSUE THREAD

**Issue by noah003** [gustavz/realtime_object_detection#41]
Have you converted Mask_RNN model to .tflite successfully?
when I run the script as shown in scripts/create_tflite_graph.sh, I got the following error
```
tensorflow/lite/toco/tooling_util.cc:908] Check failed: GetOpWithOutput(model, output_array) Specified output array "num_detections,detection_boxes,detection_scores,detection_classes,detection_masks" is not produced by any op in this graph. Is it a typo? To silence this message, pass this flag:  allow_nonexistent_arrays
```

**Comment by gustavz** [comment]
This repo is not about Mask R-CNN.

And no unfortunately as for my knowledge the mask r-cnn layers are not yet fully supported in tflite
